=== ics-upmc/Dafoe/workspace/org.dafoe.terminologiclevel/termsDictionary.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="ensTermes" type="ensTermsType">
		<xs:annotation>
			<xs:documentation>Terms dictionary</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="ensTermsType">
		<xs:sequence>
			<xs:element name="terme" type="xs:string" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== ics-upmc/Dafoe/workspace/org.dafoe.terminologiclevel/antiDictionary.xml
<?xml version="1.0" encoding="UTF-8"?>
<ensTermes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="D:\dev\dafoe4app\org.dafoe.ui.thirdparty.saillance\termsDictionary.xsd">
	<terme>Term 10</terme>
	<terme>Term 20</terme>
	<terme>Term 30</terme>
	<terme>Term 40</terme>
	<terme>Term 50</terme>
	<terme>Term 60</terme>
	<terme>Term 70</terme>
	<terme>Term 80</terme>
	<terme>Term 90</terme>
	<terme>Term 100</terme>
	<terme>Term 110</terme>
	<terme>Term 120</terme>
	<terme>Term 130</terme>	
</ensTermes>
